version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build application
          command: npm run build

      - run:
          name: Test
          command: npm test

      - store_artifacts:
          path: ./artifacts
          destination: artifacts

      - run:
          name: Send build stats to Relative CI
          command: node_modules/.bin/relative-ci-agent --webpack-stats artifacts/webpack.stats.main.json

      - run:
          name: Send coveralls
          command: cat ./artifacts/coverage/lcov.info | node_modules/.bin/coveralls

